### ISSUE TITLE
libvpx-native is missing when doing bitbake core-image-doom

### ISSUE THREAD

**Issue by thomas-roos** [JPEWdev/oe-doom-demo#2]
when doing `bitbake core-image-doom`
libvpx-native is missing
did need to add `BBCLASSEXTEND = "native nativesdk"`
here: meta-oe/recipes-multimedia/webm/libvpx_1.12.0.bb
is this correct?
But then it's failing...

**Comment by JPEWdev** [comment]
Ya, I have bending patches in upstream meta-openembeded. Once they land, this will be fixed. See
* https://lists.openembedded.org/g/openembedded-devel/message/101233
* https://lists.openembedded.org/g/openembedded-devel/message/101218
